.github/workflows/main.yml, Makefile, shared/src/utils/date.ts, web/package.json, web/src/components/BaseLayout/Header/index.tsx, web/src/components/BaseQuestionnaireResponseForm/widgets/date.tsx, web/src/components/BaseQuestionnaireResponseForm/widgets/group.tsx, web/src/components/BaseQuestionnaireResponseForm/widgets/pair-input.tsx, web/src/components/BaseQuestionnaireResponseForm/widgets/radio.tsx, web/src/components/ModalNewEncounter/index.tsx, web/src/containers/App/App.test.tsx, web/src/containers/App/index.tsx, web/src/containers/EncounterDetails/index.tsx, web/src/containers/EncounterList/hooks.ts, web/src/containers/EncounterQR/index.tsx, web/src/containers/PatientDetails/index.tsx, web/src/containers/PatientList/index.tsx, web/src/containers/PractitionerList/hooks.ts, web/src/index.tsx, web/src/setupTests.ts, yarn.lock
Add Test in github jobs
Ref #29
=> Setup tests

resources/seeds/Mapping/encounter-create.yaml, resources/seeds/Questionnaire/encounter-create.yaml, web/src/components/BaseQuestionnaireResponseForm/index.tsx, web/src/components/BaseQuestionnaireResponseForm/widgets/TimeRangePickerControl/__tests__/TimeRangePickerControl.test.ts, web/src/components/BaseQuestionnaireResponseForm/widgets/TimeRangePickerControl/hooks.ts, web/src/components/BaseQuestionnaireResponseForm/widgets/TimeRangePickerControl/index.tsx, web/src/components/BaseQuestionnaireResponseForm/widgets/TimeRangePickerControl/types.ts, web/src/components/BaseQuestionnaireResponseForm/widgets/index.ts, web/src/components/ModalNewEncounter/__test__/create-encounter.test.tsx, web/src/components/ModalNewEncounter/index.tsx, web/src/components/TimePicker/index.tsx, web/src/components/TimePicker/types.ts
=> Add separate time range picker for encounter create form

resources/seeds/Mapping/patient-create.yaml, resources/seeds/Questionnaire/patient-create.yaml, web/src/components/ModalNewPatient/__test__/create-patient.test.tsx
Add test for patient create questionnaire
Ref #54
=> Fix ssn prop saving to the patient resource

resources/seeds/Mapping/edit-appointment-extract.yaml, resources/seeds/Mapping/encounter-create.yaml, resources/seeds/Mapping/new-appointment-extract.yaml, resources/seeds/Mapping/public-appointment-extract.yaml, resources/seeds/Questionnaire/encounter-create.yaml, resources/seeds/Questionnaire/public-appointment.yaml, web/package.json, web/src/components/BaseQuestionnaireResponseForm/index.tsx, web/src/components/BaseQuestionnaireResponseForm/widgets/DateTimeSlot/DateTimeSlot.module.scss, web/src/components/BaseQuestionnaireResponseForm/widgets/DateTimeSlot/DateTimeSlot.test.ts, web/src/components/BaseQuestionnaireResponseForm/widgets/DateTimeSlot/index.tsx, web/src/components/BaseQuestionnaireResponseForm/widgets/DateTimeSlot/utils.ts, web/src/components/BaseQuestionnaireResponseForm/widgets/PractitionerRoleList/index.tsx, web/src/components/BaseQuestionnaireResponseForm/widgets/index.ts, web/src/components/ModalNewEncounter/__test__/create-encounter.test.tsx, web/src/components/ModalNewEncounter/index.tsx, web/src/components/QuestionnaireResponseForm/index.tsx, web/src/containers/App/index.tsx, web/src/containers/Appointment/PublicAppointment.module.scss, web/src/containers/Appointment/PublicAppointment.tsx, web/src/containers/PatientDetails/PatientDocument/index.tsx, web/src/containers/Scheduling/ScheduleCalendar/hooks/useCalendarOptions.ts, yarn.lock, zrc/box.edn
=> WIP Add public book appointment form

run_test.sh
=> Migrate test run to docker compose v2

web/src/components/BaseQuestionnaireResponseForm/index.tsx, web/src/components/QuestionnaireResponseForm/index.tsx, web/src/containers/DocumentsList/index.tsx, web/src/containers/PatientDetails/PatientDocument/index.tsx, web/src/containers/PatientDetails/PatientDocumentDetails/index.tsx
=> Add automatic saving of patient documents

web/src/components/BaseQuestionnaireResponseForm/index.tsx, web/src/components/QuestionnaireResponseForm/index.tsx, web/src/containers/PatientDetails/PatientDocument/index.tsx
Fix the problem with creating two questionnaire response in patient documents and use autoSave property instead of saveQuestionnaireResponseDraft
Ref: #26
=> 26 autosaving fix

web/src/containers/PatientDetails/PatientDocumentDetails/PatientDocumentDetails.module.scss, web/src/containers/PatientDetails/PatientDocumentDetails/index.tsx
=> Add button to delete patient document in in-progress status

docker-compose.yaml, shared/src/config.local.ts, shared/src/config.production.ts, web/public/index.html, web/public/index.production.html, web/src/containers/App/index.tsx, web/src/containers/PatientPortal/Wearables/Wearables.module.scss, web/src/containers/PatientPortal/Wearables/hooks.ts, web/src/containers/PatientPortal/Wearables/index.tsx, web/src/containers/PatientPortal/index.tsx, web/src/containers/SignIn/SignIn.module.scss, web/src/containers/SignIn/hooks.ts, web/src/containers/SignIn/index.tsx, web/src/setupTests.ts, web/src/sharedState/index.ts
=> OpenID authenticated patient portal wearables page

Makefile, compose.yaml
**Updates:**
1. Change the tag for SDC image from *develop* to *master*;
2. Update *seeds* command in make file.
=> Change tag for fhir-sdc from develop to master and update make seeds

src/containers/QuestionnaireBuilder/Builder/index.tsx, src/containers/QuestionnaireBuilder/PromptForm.tsx, src/containers/QuestionnaireBuilder/QuestionnaireBuilder.module.scss, src/containers/QuestionnaireBuilder/hooks.ts, src/containers/QuestionnaireBuilder/index.tsx
Ref: https://github.com/beda-software/fhir-emr/issues/209
=> Add an ability to pick previous version of the Questionnaire

src/containers/PatientDetails/PatientApps/__tests__/useLaunchApp.test.ts, src/containers/PatientDetails/PatientApps/hooks.ts, src/containers/PatientDetails/PatientApps/index.tsx
fixed Smart App crashes for Patient and Super admin
=> #214 fixed Smart App crashes for Patient and Super admin

src/containers/PatientDetails/PatientApps/__tests__/useSmartApps.test.ts
=> #247 Introduce two types of smart apps

src/containers/PatientDetails/PatientDocumentDetails/index.tsx
=> Update condition for questionnaire response editing

src/containers/EncounterList/__tests__/EncounterList.test.ts
=> Fix encounter list test

src/containers/EncounterDetails/hooks.ts, src/containers/EncounterDetails/index.tsx
Let VideoCall get the same parameters via location.state both from EncountersList and from EncounterDetails
=> Fix and unify location state sent to VideoCall

src/components/SearchBar/SearchBarColumn/ChoiceColumn/__tests__/ChoiceColumn.test.ts, src/components/SearchBar/types.ts
=> #267 Made options field is required in ChoiceColumn

src/containers/InvoiceList/components/InvoiceListSearchBar/InvoiceListSearchBar.styles.ts, src/containers/InvoiceList/index.tsx
This pull request addresses the layout issues described in Issue #295. The changes improve the responsiveness of the `InvoiceList` component on mobile devices to ensure a better user experience.
- **Added `flex-wrap: wrap;` to the `SelectContainer`** in `InvoiceListSearchBar` to ensure that the search bar items wrap correctly on smaller screens.
- **Added `scroll={{ x: 'max-content' }}` to the `Table` component** in `InvoiceList` to enable horizontal scrolling on smaller devices.
A screen recording demonstrating the new responsive behavior on mobile devices:
This PR fixes #295.
Please review the changes and let me know if further adjustments are needed. Thank you!
For more details on the Ant Design Table component and its responsive features, please refer to the documentation: [Ant Design …
=> #295 Fix invoices layout 

src/utils/fhirpath.ts
Following
https://gist.github.com/ruscoder/ded33efb559ba480140ddf16e60fa3e7
=> Add definitions for typed fhirpath compile

src/components/BaseQuestionnaireResponseForm/readonly-widgets/display.tsx, src/components/BaseQuestionnaireResponseForm/widgets/display.tsx
Refs: https://github.com/beda-software/fhir-emr/issues/322
=> Make display with link clickable

contrib/aidbox-types/index.d.ts, src/components/BaseQuestionnaireResponseForm/widgets/QuestionQuantity.stories.tsx, src/components/BaseQuestionnaireResponseForm/widgets/number.tsx, src/utils/converter/fhirToFce/questionnaire/processItems.ts
https://github.com/beda-software/fhir-emr/issues/323
=> Add unitOption

src/containers/DocumentsList/ChooseDocumentToCreateModal/index.tsx, src/containers/EncounterDetails/hooks.ts, src/containers/EncounterDetails/index.tsx, src/containers/PatientDetails/PatientDocuments/index.tsx
Ref https://github.com/RSDUE/rsdue_emr/issues/203
=> Add an option to open Patient's questionnaires in new tab

src/containers/PatientDetails/PatientOverviewDynamic/components/StartEncounter/useStartEncounter.ts
Ref https://github.com/RSDUE/rsdue_emr/issues/215
=> Add condition to parse encounter as FHIR resource

resources/seeds/Mapping/crp-extract.yaml, resources/seeds/Mapping/il6-extract.yaml, resources/seeds/Mapping/labs.yaml, resources/seeds/Mapping/pct-extract.yaml, resources/seeds/Questionnaire/crp.yaml, resources/seeds/Questionnaire/il6.yaml, resources/seeds/Questionnaire/labs.yaml, resources/seeds/Questionnaire/pct.yaml, src/containers/PatientDetails/PatientOrders/index.tsx
- Add Lab biomarkers to Encounter > New document
- Add lab biomarkers orders
=> Add new lab orders

src/components/QuestionnaireResponseForm/index.tsx, src/containers/PatientDetails/PatientDocument/usePatientDocument.ts, src/containers/PatientDetails/PatientOverviewDynamic/components/LinkToEdit/index.tsx
Added condition operator to onFormResponse entry.resource
Get last added provenance in usePatientDocument hook
=> Check all provenance targets in linktoedit component

resources/seeds/Questionnaire/repeatable-group.yaml, src/components/BaseQuestionnaireResponseForm/widgets/Group/RepeatableGroups/__tests__/RepeatableGroups.test.tsx, src/components/BaseQuestionnaireResponseForm/widgets/Group/RepeatableGroups/index.tsx, src/components/BaseQuestionnaireResponseForm/widgets/Group/index.tsx, src/containers/PatientDetails/PatientDocument/index.tsx, src/containers/PatientDetails/PatientDocument/usePatientDocument.ts, src/setupTests.ts
Pass response resource to patient document onSuccess callback which usefull for testing
Added test for repeatable group
=> Add workaround to repeatable group to store it's state

src/components/BaseQuestionnaireResponseForm/widgets/number.tsx
Value for QuestionQuantity is received as an object 
```
{
value: ..
code: ..
display: ..
system:..
}
```
=> PATCH: QuestionQuantity used wrong path to initial value

src/utils/enableWhen.ts
Ref: https://github.com/beda-software/fhir-emr/issues/437
=> PATCH: enableWhen util to handle empty arrays

src/components/BaseLayout/Footer/Footer.styles.ts, src/components/BaseLayout/Footer/index.tsx, src/components/BaseQuestionnaireResponseForm/widgets/QuestionDateTime.stories.tsx, src/containers/EncounterDetails/AIScribe/index.tsx, src/containers/HealthcareServiceList/index.tsx, src/containers/InvoiceList/components/InvoiceListSearchBar/hooks.ts, src/locale/en/messages.po, src/locale/es/messages.po, src/locale/ru/messages.po, src/utils/relative-date.ts
Hi, we need to add these translations to the master branch. It includes some changes in the code in addition to the messages.po file.
Best regards.
Madeleyne
=> add new translations

package.json, src/containers/InvoiceList/tableUtils.tsx, src/containers/InvoiceList/types.ts, yarn.lock
Brings `usePager` with `set` function to update response without reloading
=> Bump fhir-react version to 1.8.7

resources/seeds/Questionnaire/group-wizard-test.yaml, src/components/BaseQuestionnaireResponseForm/widgets/GroupWizard/__tests__/GroupWizard.test.tsx, src/components/BaseQuestionnaireResponseForm/widgets/GroupWizard/index.tsx, src/components/Wizard/Wizard.stories.tsx, src/components/Wizard/index.tsx, src/utils/questionnaire.ts
Added force rhf trigger calling on step changing after form is submitted
=> Fixed wizard skiped steps validation

resources/seeds/Device/ai-agent.yaml, resources/seeds/Practitioner/ai-agent.yaml, src/containers/PatientDetails/Dashboard/config.ts, src/containers/PatientDetails/PatientOverviewDynamic/components/SummaryCard/index.tsx, src/containers/PatientDetails/PatientOverviewDynamic/containers/SummaryCardContainer/hooks.ts, src/containers/PatientDetails/PatientOverviewDynamic/containers/SummaryCardContainer/index.tsx, src/services/ai-summary.test.ts, src/services/ai-summary.ts, src/utils/constants.ts
=> feat: Add patient AI summary dashboard element

src/containers/PatientDetails/PatientOverviewDynamic/components/SummaryCard/index.tsx, src/containers/PatientDetails/PatientOverviewDynamic/containers/SummaryCardContainer/hooks.ts, src/containers/PatientDetails/PatientOverviewDynamic/containers/SummaryCardContainer/index.tsx, src/locale/en/messages.po, src/locale/es/messages.po, src/locale/ru/messages.po, src/services/ai-summary.ts
In case of error:
- Show notification
- Remove loader from Update button
=> Use remote data for AI Summary update button

src/components/BaseQuestionnaireResponseForm/controls.tsx, src/components/BaseQuestionnaireResponseForm/widgets/string.tsx, src/utils/questionnaire.ts
ref #https://github.com/breeoot/ehr/issues/803
=> Add email trim() and email() mask

src/components/BaseQuestionnaireResponseForm/widgets/Group/RepeatableGroups/__tests__/RepeatableGroups.adding.test.tsx, src/containers/PatientDetails/PatientDocument/index.tsx, src/setupTests.ts
Deleting repeatable-group QRs after each test case running
=> Changed getFHIRResources to getAllFHIRResources

src/components/BaseQuestionnaireResponseForm/ReadonlyQuestionnaireResponseForm.tsx, src/components/BaseQuestionnaireResponseForm/readonly-widgets/date.tsx, src/utils/date.ts
ref  to task #https://github.com/breeoot/ehr/issues/767
=> 767 update time questionare form

resources/seeds/Questionnaire/heavy-menstrual-bleeding.yaml
Ref https://github.com/beda-software/fhir-emr/issues/511
=> Added heavy-menstrual-bleeding questionnaire

src/containers/QuestionnaireBuilder/QuestionnaireSaveForm/__tests__/utils.test.ts, src/containers/QuestionnaireBuilder/QuestionnaireSaveForm/index.tsx, src/containers/QuestionnaireBuilder/QuestionnaireSaveForm/utils.ts
Added removing encounter item and caunchContext if there is not Enounter in subjectType
=> Added removing encounter item and caunchContext

src/uberComponents/ResourceListPage/BatchActions.tsx, src/uberComponents/ResourceListPage/actions.tsx, src/uberComponents/ResourceListPage/index.tsx, src/uberComponents/ResourceListPage/types.ts, src/uberComponents/ResourceListPageContent/index.tsx
- allows to pass custom controls to batch actions;
- pass `selectedResourcesBundle` as `getBatchActions` argument.
=> Add custom actions support in batch actions

src/components/BaseLayout/PageContainer/index.tsx, src/uberComponents/ResourceListPage/hooks.ts, src/uberComponents/ResourceListPage/index.tsx
=> Add back button to resource list page

src/components/QuestionnairesWizard/hooks.tsx
- Update pre-submit validation to check against questionnaireResponses instead of arbitrary stepStatuses
- Update handleCancel to not override onCancel from props
=> QuestionnairesWizard patch

src/components/BaseQuestionnaireResponseForm/widgets/GroupWizard/GroupWizard.stories.tsx, src/components/BaseQuestionnaireResponseForm/widgets/GroupWizard/index.tsx, src/components/QuestionnairesWizard/components/QuestionnairesWizardFooter/index.tsx, src/components/QuestionnairesWizard/hooks.tsx, src/components/QuestionnairesWizard/index.tsx, src/components/Wizard/Wizard.stories.tsx, src/components/Wizard/styles.ts, src/containers/PatientDetails/PatientDocumentWizard/index.tsx
- display finished state
- optionally enable/disable free navigation to 'wait' steps
- refactor styles to use helpers
=> Update Wizard steps styles
